.TH accustamp 1
.SH NAME
accustamp \- put a precise timestamp on each line
.SH SYNOPSIS
.B accustamp
.SH DESCRIPTION
.B accustamp
prints an accurate timestamp and a space,
copies a line of text from its input,
and repeats.

The timestamp is the number of seconds since 1969 TAI,
to microsecond precision,
printed in decimal.

.B accustamp
exits 0
on EOF or error.
.SH "SEE ALSO"
tailocal(1),
gettimeofday(2)
