.TH svstat 1
.SH NAME
svstat \- print the status of a supervised service
.SH SYNOPSIS
.B svstat
.I dir ...
.SH DESCRIPTION
.B svstat
prints the status of a
.BR supervise -monitored
service.
.I dir
is the same directory
used for
.BR supervise .

You can list several
.IR dir s.
.B svstat
will print the status of each service in turn.
.SH "SEE ALSO"
supervise(1)
