.TH tailocal 1
.SH NAME
tailocal \- convert TAI timestamps to local time
.SH SYNOPSIS
.B tailocal
.SH DESCRIPTION
.B tailocal
reads a line of input,
looks for a TAI timestamp at the beginning of the line,
prints the line with the timestamp converted to local time,
and repeats.

TAI timestamps are numbers.
Local time is YYYY/MM/DD HH:MM:SS.
.SH "SEE ALSO"
accustamp(1),
localtime(3)
