.TH usually 1
.SH NAME
usually \- copy input to output, checking for anomalous lines
.SH SYNOPSIS
.B usually
.I patternfile
.SH DESCRIPTION
.B usually
copies lines from stdin to stdout.
It expects each line to match at least one of the patterns listed
in
.IR patternfile .
If a line does not match,
.B usually
prints it to stderr.

To keep its memory use bounded,
.B usually
truncates long lines to 500 characters
before checking them against
.I patternfile
and printing them to stderr.
It does not truncate the copy printed to stdout.

If
.B usually
receives a HUP signal,
it reads
.I patternfile
again.
.SH PATTERNS
.I patternfile
contains a set of patterns, one pattern per line.
A pattern is a string of characters and wildcards.
A wildcard matches any string of characters that does
.I not
include the next character in the pattern.

For example, the pattern

.EX
* tcpcontrol: ok * *:*:25 *
.EE

matches any line that consists of
(1) non-space characters followed by a space;
(2) tcpcontrol:_ok_;
(3) non-space characters followed by a space;
(4) non-colon characters followed by a colon;
(5) non-colon characters followed by a colon;
(6) 25_; and
(7) any characters followed by a newline.

.B usually
always matches blank lines and partial final lines.
.SH "SEE ALSO"
writeerr(1)
